config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get 'welcome/index'

  
  resources :artifacts do
    member do
      delete :delete_image_attachment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artifact.rb
class Artifact < ApplicationRecord

    validates :name, presence: true, length: {minimum: 5}

    has_one_attached :image

    def self.search(search)
        where("name LIKE ? OR inventory_number LIKE ? OR museum_name LIKE ? OR collection LIKE ? OR era LIKE ? OR creator LIKE ? OR owner LIKE ? OR acquisition LIKE ? OR revision_date LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
    end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login
  validate :validate_username

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController

    before_action :authenticate_user!, except: [:show, :index]

    def index
        @artifacts = Artifact.all
        if params[:search]
            @artifacts = Artifact.search(params[:search]).order("created_at DESC")
          else
            @artifacts = Artifact.all.order("created_at DESC")
        end
    end
    
    def show
        @artifact = Artifact.find(params[:id])
    end
    
    def new
        @artifact = Artifact.new
    end

    def edit
        @artifact = Artifact.find(params[:id])
    end

    def create
        @artifact = Artifact.new(artifact_params)
        
        if @artifact.save
            redirect_to @artifact
        else
            render 'new'
        end
    end

    def update
        @artifact = Artifact.find(params[:id])

        if @artifact.update(artifact_params)
            redirect_to @artifact
        else
            render 'edit'
        end
    end

    def destroy
        @artifact = Artifact.find(params[:id])
        @artifact.destroy
        redirect_to artifacts_path
    end

    def delete_image_attachment
        @image = ActiveStorage::Attachment.find(params[:id])
        @image.purge
        redirect_back(fallback_location: request.referer)
    end

    private
        def artifact_params
            params.require(:artifact).permit(:name,:inventory_number, :museum_name, :collection, :era, :creator,
            :quantity, :owner, :acquisition, :price, :inventory_by, :revision_date, :revision_by, :description, :image)
        end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artifacts/_form.html.erb
<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet">

<%= form_with model: @artifact, local: true do |form| %>
  <% if @artifact.errors.any? %>
    <div id= "error_explanation">
      <h2>
        <%= pluralize(@artifact.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @artifact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
  <div class ="box-details">
    <p>
      <%= form.text_field :name, class: 'form-control', placeholder: 'Név' %>
    </p>
    <p>
      <%= form.text_field :inventory_number, class: 'form-control', placeholder: "Leltárszám" %>
    </p>
    <p>
      <%= form.text_field :museum_name, class: 'form-control', placeholder: "Múzeum"  %>
    </p>
    <p>
      <%= form.select :collection, options_for_select(['Vaskori Gyűjtemény', 'Római Gyűjtemény', 'Népvándorláskori Gyűjtemény', 'Középkori Gyűjtemény']),{}, class: "form-control" %>
    </p>
    <p>
      <%= form.text_field :era, class: 'form-control', placeholder: "Keltezés" %>
    </p>
    <p>
      <%= form.text_field :creator, class: 'form-control', placeholder: "Készítő" %>
    </p>
    <p>
      <%= form.number_field :quantity, min: "1", class:'form-control', placeholder: "Mennyiség" %>
    </p>
    <p>
      <%= form.text_field :owner, class: 'form-control', placeholder: "Tulajdonos" %>
    </p>
    <p>
      <%= form.text_field :acquisition, class: 'form-control', placeholder: "Beszerzés" %>
    </p>
    <p>
      <%= form.number_field :price, min: "0", class: 'form-control', placeholder: "Ár" %>
    </p>
    <p>
      <%= form.text_field :inventory_by, class: 'form-control', placeholder: "Beleltározta" %>
    </p>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">Revízió dátuma</span>
        <%= form.date_field :revision_date, class: 'form-control input-group date' %>
      </div>
      
    </div>
    <p>
      <%= form.text_field :revision_by, class: 'form-control', placeholder: "Revíziót végezte" %>
    </p>
  </div>
  <div class="description-box">
    <p>
      <%= form.text_area :description, size: "30x5", class: 'form-control', placeholder: "Leírás"%>
    </p>
    <p>
      <% if @artifact.image.attached? == false %>
        <%= form.label :kép_hozzáadása %>
        <%= form.file_field :image %>
      <% else @artifact.image.previewable? %>
        <%= image_tag(@artifact.image, style: "height: 30em") %>
        <%= link_to 'Kép eltávolítása', delete_image_attachment_artifact_url(@artifact.image.id),
            method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light" %>
      <% end %>
    </p>
    <p>
      <%= form.submit :Mentés, class: 'btn btn-info'%>
    </p>
    <%= link_to 'Műtárgyak listája', artifacts_path, :class => "btn btn-light" %>
  </div>
  </div>
<% end %>

app/views/artifacts/edit.html.erb
<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet">

  <h1 class = "title">Műtárgy szerkesztése</h1>
  <%= render 'form' %>
  

app/views/artifacts/index.html.erb
<%= render 'layouts/login' %>
<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet">

<nav  id="navbarid" class="navbar navbar-dark bg-dark">
	<div id="conatainerid" class="container">
		<%= link_to 'Új műtárgy', new_artifact_path, :class =>"btn btn-dark" %>
    <a class="navbar-brand">Műtárgyak listája</a>    
    <form class="form-inline">
      <%= form_tag(artifacts_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Keresés" %>
        <%= submit_tag "Keresés", :name => nil, class: 'btn btn-dark' %>
      <% end %>
    </form>
</nav>

<% if @artifacts.blank? %>
  <p>Az adatbázisban nem található <%= params[:search] %> kifejezés.</p>
<% end %>

<div class="overflow-x:auto">
  <table style="width: auto;" id="tableid", class="table table-hover table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="col">Megnevezés</th>
        <th class="col">Leltárszám</th>
        <th class="col">Múzeum</th>
        <th class="col">Gyűjtemény</th>
        <th class="col">Korszak</th>
        <th class="col">Készítő</th>
        <th class="col07">Mennyiség</th>
        <th class="col">Tulajdonos</th>
        <th class="col">Beszerzés</th>
        <th class="col10">Ár</th>
        <th class="col">Beleltározta</th>
        <th class="col">Revízió dátuma</th>
        <th class="col">Revíziót végezte</th>
        <th class="col">Leírás</th>
        <th class="col15">Műveletek</th>
      </tr>
    </thead>
    <tbody>
      <% @artifacts.each do |artifact| %>
        <tr>
          <td><%= artifact.name %></td>
          <td><%= artifact.inventory_number %></td>
          <td><%= artifact.museum_name %></td>
          <td><%= artifact.collection %></td>
          <td><%= artifact.era %></td>
          <td><%= artifact.creator %></td>
          <td><%= artifact.quantity %></td>
          <td><%= artifact.owner %></td>
          <td><%= artifact.acquisition %></td>
          <td><%= artifact.price %></td>
          <td><%= artifact.inventory_by %></td>
          <td><%= artifact.revision_date %></td>
          <td><%= artifact.revision_by%></td>
          <td class="row14"><%= artifact.description %></td>
          <td>
            <%= link_to artifact_path(artifact) do %>
              <svg class="bi bi-eye-fill" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/><path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
              </svg>
            <% end %>
            <%= link_to edit_artifact_path(artifact) do %>
              <svg class="bi bi-pencil" width="2em" height="2em" viewBox="0 0 16 16" fill="green" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"/>
                <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"/>
              </svg>
            <% end %><br>
            <%= link_to artifact_path(artifact), method: :delete, data: {confirm: 'Biztosan törölni szeretné a kiválasztott tárgyat?'} do %>
              <svg class="bi bi-trash" width="2em" height="2em" viewBox="0 0 16 16" fill="red" xmlns="http://www.w3.org/2000/svg">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Főlista', artifacts_path, :class => "btn btn-light" %>
</div>

app/views/artifacts/new.html.erb
<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet">

  <h1 class ="title">Új műtárgy</h1>
  <%= render 'form' %>

app/views/artifacts/show.html.erb
<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet">
<div class="container-show">
  <div class= "box-details-show">
    <div>
      <strong>Név:</strong>
      <%= @artifact.name %>
    </div>
    <br>
    <div>
      <strong>Leltárszám:</strong>
      <%= @artifact.inventory_number %>
    </div>
    <br>
    <div>
      <strong>Múzeum:</strong>
      <%= @artifact.museum_name %>
    </div>
    <br>
    <div>
      <strong>Gyűjtemény:</strong>
      <%= @artifact.collection %>
    </div>
    <br>
    <div>
      <strong>Korszak:</strong>
      <%= @artifact.era %>
    </div>
    <br>
    <div>
      <strong>Készítő:</strong>
      <%= @artifact.creator %>
    </div>
    <br>
    <div>
      <strong>Mennyiség:</strong>
      <%= @artifact.quantity %>
    </div>
    <br>
    <div>
      <strong>Tulajdonos:</strong>
      <%= @artifact.owner %>
    </div>
    <br>
    <div>
      <strong>Beszerzés:</strong>
      <%= @artifact.acquisition %>
    </div>
    <br>
    <div>
      <strong>Ár:</strong>
      <%= @artifact.price %>
    </div>
    <br>
    <div>
      <strong>Beleltározta:</strong>
      <%= @artifact.inventory_by %>
    </div>
    <br>
    <div>
      <strong>Revízió dátuma:</strong>
      <%= @artifact.revision_date %>
    </div>
    <br>
    <div>
      <strong>Revíziót végezte:</strong>
      <%= @artifact.revision_by %>
    </div>
    <br>
  </div>
  <div class="description-box-show">
    <div>
      <strong>Leírás:</strong>
      <%= @artifact.description %>
    </div>
    <br>
    <div>
      <% if @artifact.image.attached? == false %>
        <p>Nincs hozzácsatolt kép.</p>
      <% else @artifact.image.previewable? %>
        <%= image_tag(@artifact.image, style: "width:40%") %>
      <% end %>
    </div>
  </div>
</div>
<%= link_to 'Szerkesztés', edit_artifact_path(@artifact), :class => "btn btn-light" %>
<%= link_to 'Műtárgyak listája', artifacts_path, :class => "btn btn-light" %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_login.html.erb
<% if current_user %>
    <%= current_user.username %><br>
    <%= link_to 'Kilépés', destroy_user_session_path, method: :delete, :class => "btn btn-light" %>
    <%= link_to 'Adatok módosítása', edit_user_registration_path, :class => "btn btn-light" %>
<% else %>
    <%= link_to 'Regisztráció', new_user_registration_path, :class =>"btn btn-light" %>
    <%= link_to 'Bejelentkezés', new_user_session_path, :class => "btn btn-light" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Museumdb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    
    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet"> 

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
                <h1 class="login-heading mb-4">&nbsp Múzeumi Adatbázis</h1>
                    <%= render 'layouts/login' %>                         
                    <%= link_to 'Műtárgyak listája', artifacts_path, :class => "btn btn-light" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Múzeumi Adatbázis</h1>
<%= link_to 'Artifacts', controller: 'atrifacts' %>